Controllers/DanhMucController.cs
using QuanLyHoSoCongChung.Models;
using QuanLyHoSoCongChung.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyHoSoCongChung.Controllers
{
    public class DanhMucController : Controller
    {
        GenericRepository<NhanVien> _context = null;
        GenericRepository<CongChungVien> _contextCCV = null;
        GenericRepository<KhachHang> _contextKH = null;
        GenericRepository<LoaiCongChung> _contextLCC = null;
        GenericRepository<AccountNhanVien> _contextAcc = null;
        private NhanVienRp _obj = new NhanVienRp();
        private CongChungVienRp _objCCV = new CongChungVienRp();
        private KhachHangRp _objKH = new KhachHangRp();
        private LoaiCongChungRp _objLCC = new LoaiCongChungRp();
        private AccNhanVienRp _objANV = new AccNhanVienRp();

        // GET: DanhMuc
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Get_Role()
        {
            List<Role> result = _objANV.Role_GetList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AccountNhanVien()
        {
            var session = Session["UserID"];
            var role = Session["Role"];
            var name = Session["UserName"];
            ViewBag.User = name;
            ViewBag.Role = role;
            return View();
            //if (session != null)
            //{
            //    var role = Session["Role"].ToString();
            //    if (role == "1")
            //    {
            //        ViewBag.User = name;
            //        return View();
            //    }
            //    else
            //    {
            //        return RedirectToAction("Login", "Admin");
            //    }
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Admin");
            //}
        }
        public ActionResult Get_AccNhanVien(int pageSize, int pageIndex, string strTen)
        {
            List<AccountNhanVienGet> result = _objANV.AccNhanVien_GetList(pageSize, pageIndex, strTen);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public string Insert_AccNhanVien(AccountNhanVien model)
        {
            _contextAcc = new GenericRepository<AccountNhanVien>();
            if (model != null)
            {
                AccountNhanVien nv = new AccountNhanVien();
                nv.Email = model.Email;
                nv.Password = model.Password;
                nv.FullName = model.FullName;
                nv.Phone = model.Phone;
                nv.Role = model.Role;
                _contextAcc.Insert(nv);
                _contextAcc.Save();
                return "Thêm thành công";
            }
            else
            {
                return "Thêm thất bại";
            }
        }
        public string Update_AccNhanVien(AccountNhanVien model)
        {
            _contextAcc = new GenericRepository<AccountNhanVien>();
            if (model != null)
            {
                AccountNhanVien nv = new AccountNhanVien();
                nv.ID = model.ID;
                nv.Email = model.Email;
                nv.Password = model.Password;
                nv.FullName = model.FullName;
                nv.Phone = model.Phone;
                nv.Role = model.Role;
                _contextAcc.Update(nv);
                _contextAcc.Save();
                return "Sửa thành công";
            }
            else
            {
                return "Sửa thất bại";
            }
        }
        public string Delete_AccNhanVien(AccountNhanVien model)
        {
            _contextAcc = new GenericRepository<AccountNhanVien>();
            if (model != null)
            {
                int x = model.ID;
                _contextAcc.Delete(x);
                _contextAcc.Save();
                return "Xóa thành công";
            }
            else
            {
                return "Xóa thất bại";
            }
        }

        public ActionResult NhanVien()
        {
            return View();
        }

        public int Count_NhanVien(int DieuKien)
        {
            int res = _obj.GetCount(DieuKien);
            return res;
        }

        [HttpGet]
        public ActionResult Get_NhanVien(int pageSize, int pageIndex, string strTen)
        {
            List<NhanVien> result = _obj.NhanVien_GetList(pageSize, pageIndex, strTen);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public string Insert_NhanVien(NhanVien model)
        {
            _context = new GenericRepository<NhanVien>();
            if (model != null)
            {
                NhanVien nv = new NhanVien();
                nv.FullNameNV = model.FullNameNV;
                nv.SoDienThoai = model.SoDienThoai;
                _context.Insert(nv);
                _context.Save();
                return "Successfully";
            }
            else
            {
                return "Not Inserted";
            }
        }

        public string Update_NhanVien(NhanVien model)
        {
            _context = new GenericRepository<NhanVien>();
            if (model != null)
            {
                NhanVien nv = new NhanVien();
                nv.IDNhanVien = model.IDNhanVien;
                nv.FullNameNV = model.FullNameNV;
                nv.SoDienThoai = model.SoDienThoai;
                _context.Update(nv);
                _context.Save();
                return "Successfully";
            }
            else
            {
                return "Not edit";
            }
        }

        public string Delete_NhanVien(NhanVien model)
        {
            _context = new GenericRepository<NhanVien>();
            if (model != null)
            {
                int x = model.IDNhanVien;
                _context.Delete(x);
                _context.Save();
                return "Successfully";
            }
            else
            {
                return "Not delete";
            }
        }

        public ActionResult KhachHang()
        {
            //var session = Session["UserID"];
            //var name = Session["UserName"];
            //ViewBag.User = name;
            var session = Session["UserID"];
            var role = Session["Role"];
            var name = Session["UserName"];
            ViewBag.User = name;
            ViewBag.Role = role;
            return View();
        }

        public ActionResult Get_KhachHang(int pageSize, int pageIndex, string strTen)
        {
            List<KhachHang> result = _objKH.KhachHang_GetList(pageSize, pageIndex, strTen);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public string Insert_KhachHang(KhachHang model)
        {
            _contextKH = new GenericRepository<KhachHang>();
            if (model != null)
            {
                //if (model.)
                KhachHang kh = new KhachHang();
                kh.TenKhachHang = model.TenKhachHang;
                kh.CoQuan = model.CoQuan;
                kh.SoDienThoai = model.SoDienThoai;
                _contextKH.Insert(kh);
                _contextKH.Save();
                return "Thêm mới thành công";
            }
            else
            {
                return "Thêm mới thất bại";
            }
        }
        public string Update_KhachHang(KhachHang model)
        {
            _contextKH = new GenericRepository<KhachHang>();
            if (model != null)
            {
                KhachHang kh = new KhachHang();
                kh.IDKhachHang = model.IDKhachHang;
                kh.TenKhachHang = model.TenKhachHang;
                kh.CoQuan = model.CoQuan;
                kh.SoDienThoai = model.SoDienThoai;
                _contextKH.Update(kh);
                _contextKH.Save();
                return "Sửa thành công";
            }
            else
            {
                return "Sửa thất bại";
            }
        }
        public string Delete_KhachHang(KhachHang model)
        {
            _contextKH = new GenericRepository<KhachHang>();
            if (model != null)
            {
                int x = model.IDKhachHang;
                _contextKH.Delete(x);
                _contextKH.Save();
                return "Xóa thành công";
            }
            else
            {
                return "Xóa thất bại";
            }
        }

        public ActionResult CongChungVien()
        {
            //var session = Session["UserID"];
            //var name = Session["UserName"];
            //ViewBag.User = name;
            var session = Session["UserID"];
            var role = Session["Role"];
            var name = Session["UserName"];
            ViewBag.User = name;
            ViewBag.Role = role;
            return View();
        }

        public ActionResult Get_CongChungVien(int pageSize, int pageIndex, string strTen)
        {
            List<CongChungVien> result = _objCCV.CongChungVien_GetList(pageSize, pageIndex, strTen);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public string Insert_CongChungVien(CongChungVien model)
        {
            _contextCCV = new GenericRepository<CongChungVien>();
            if (model != null)
            {
                CongChungVien ccv = new CongChungVien();
                ccv.FullNameCCV = model.FullNameCCV;
                ccv.SoDienThoai = model.SoDienThoai;
                _contextCCV.Insert(ccv);
                _contextCCV.Save();
                return "Thêm mới thành công";
            }
            else
            {
                return "Thêm mới thất bại";
            }
        }

        public string Update_CongChungVien(CongChungVien model)
        {
            _contextCCV = new GenericRepository<CongChungVien>();
            if (model != null)
            {

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="#" type="/Asses/image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/Asses/css/bootstrap.min.css">
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="/Asses/css/pogo-slider.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="/Asses/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/Asses/css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/Asses/css/custom.css">
    <link rel="stylesheet" href="~/Asses/css/MyStyle.css" />

    @*<link href="~/Asses/datapicker/jquery-ui.css" rel="stylesheet" />
    
    <script type="text/javascript" src="~/Asses/datapicker/jquery-ui.min.js"></script>*@

    <script type="text/javascript" src="~/Asses/js/jquery.min.js"></script>

    @*<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"></script>*@


</head>

<body id="about_us" data-spy="scroll" data-target="#navbar-wd" data-offset="98">
    <!-- LOADER -->
    <div id="preloader">
        <div class="loader">
            <img src="/Asses/images/loader.gif" alt="#" />
        </div>
    </div>
    <!-- end loader -->
    <div class="header" style="height:50px;">
        <header class="top-header">
            <nav class="navbar header-nav navbar-expand-lg" style="padding-bottom:0px;padding-top:0px">
                <div class="container-fluid">
                    <a class="navbar-brand" href="~/home/index"><img src="~/Asses/images/logo-vnpt(1).png" alt="image" style="height:50px;"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                        <ul class="navbar-nav">
                            <li><a class="nav-link active menu-a" href="@Url.Action("Index", "Home")">Quản lý hồ sơ</a></li>

                            @*<a class="nav-link" href="about.html">Danh mục</a>*@
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle menu-a" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Danh mục
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:DodgerBlue">
                                    <a class="dropdown-item" href="@Url.Action("AccountNhanVien", "DanhMuc")">Nhân viên</a>
                                    <a class="dropdown-item" href="@Url.Action("KhachHang", "DanhMuc")">Khách hàng</a>
                                    <a class="dropdown-item" href="@Url.Action("CongChungVien", "DanhMuc")">Công chứng viên</a>
                                    <a class="dropdown-item" href="@Url.Action("LoaiCongChung", "DanhMuc")">Loại công chứng</a>
                                    <div class="dropdown-divider"></div>
                                    @*<a class="dropdown-item" href="#">Something else here</a>*@
                                </div>
                            </li>
                            <li><a class="nav-link menu-a" href="@Url.Action("BaoCao", "Home")">Báo cáo</a></li>
                            <li><a class="nav-link menu-a" href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                            @if (@ViewBag.User != null)
                            {
                                @*<li><a class="nav-link active" style="background:#fff;color:#000;" href="#">@ViewBag.User</a></li>*@
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle menu-a" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @ViewBag.User
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:DodgerBlue">
                                        <a class="dropdown-item" href="@Url.Action("Logout", "Admin")">Đăng xuất</a>
                                        <div class="dropdown-divider"></div>
                                        @*<a class="dropdown-item" href="#">Something else here</a>*@
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li><a class="nav-link active" style="background:#fff;color:#000;" href="contact.html">Tài khoản</a></li>
                            }

                        </ul>
                    </div>
                    @*<div class="search-box">
                            <input type="text" class="search-txt" placeholder="Search">
                            <a class="search-btn">
                                <img src="/Asses/images/search_icon.png" alt="#" />
                            </a>
                        </div>*@
                </div>
            </nav>
        </header>
    </div>
    <br />

    <div>
        @RenderBody()
    </div>

    <br />
    <div class="footer">
        <footer class="footer-box" style="height:25px;padding-top: 10px;padding-bottom: 40px;">
            <p style="margin-bottom:10px">@DateTime.Now.Year - Quản lý hồ sơ công chứng - CNTT - Viễn thông Bắc Ninh</p>
        </footer>
    </div>

    <!-- ALL JS FILES -->
    <script src="/Asses/js/jquery.min.js"></script>
    @*<script src="~/Asses/datapicker/jquery-ui.min.js"></script>*@
    @*<script src="~/Asses/js/jquery-3.5.1.slim.min.js"></script>*@
    <script src="/Asses/js/popper.min.js"></script>
    <script src="/Asses/js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="/Asses/js/bootstrap.min.js"></script>
    <script src="/Asses/js/jquery.magnific-popup.min.js"></script>
    <script src="/Asses/js/jquery.pogo-slider.min.js"></script>
    <script src="/Asses/js/slider-index.js"></script>
    <script src="/Asses/js/smoothscroll.js"></script>
    <script src="/Asses/js/form-validator.min.js"></script>
    <script src="/Asses/js/contact-form-script.js"></script>
    <script src="/Asses/js/isotope.min.js"></script>
    <script src="/Asses/js/images-loded.min.js"></script>
    <script src="/Asses/js/custom.js"></script>
    <!-- ANGULAR -->
    <script src="~/Asses/js/angular.min.js"></script>

</body>

</html>